[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\services\data_publishing_service'

[projects.cd]
path = 'Source\Data Publishing Service.lvproj'

[[build.steps]]
name = 'Data Publishing Service Support'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Data Publishing Service Support'

[[build.steps]]
name = 'Data Publishing Service Launcher'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Data Publishing Service Launcher'

[package]
type = 'nipkg'
name = 'ni-data-publishing-service-{veristand_version}'
dev_xml_path = 'Source\Ignore.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2019_release_branches = ["master",]